require: rubocop-rspec

inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false
